lexik_jwt_authentication:
    user_id_claim: user_identifier
    secret_key: "%env(resolve:JWT_SECRET_KEY)%"
    public_key: "%env(resolve:JWT_PUBLIC_KEY)%"
    pass_phrase: "%env(JWT_PASSPHRASE)%"
    token_ttl:  3600 # 1 hour
    remove_token_from_body_when_cookies_used: false
    set_cookies:
        BEARER: 
            samesite: none
            path: /
            domain: null 
            secure: true 
            httpOnly: true
            partitioned: true

    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization
        cookie:
            enabled: false
            name: BEARER

    encoder:
        # service: lexik_jwt_authentication.encoder.lcobucci # default encoder
        service: App\Security\JwtCustomEncoder #// only works for authorization_header, cookies its not working for now.

        # encryption algorithm used by the encoder service
        signature_algorithm: RS256
    blocklist_token:
        enabled: true
        cache: cache.app
